apiVersion: apps/v1
kind: Deployment
metadata:
  name: teri-coaching
spec:
  replicas: 1
  revisionHistoryLimit: 3
  selector:
    matchLabels:
      app: teri-coaching
  template:
    metadata:
      labels:
        app: teri-coaching
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      containers:
        - name: teri-coaching
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 80
          resources:
            requests:
              memory: {{ .Values.resources.requests.memory }}
              cpu: {{ .Values.resources.requests.cpu }}
            limits:
              memory: {{ .Values.resources.limits.memory }}
              cpu: {{ .Values.resources.limits.cpu }}
