apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: teri-coaching
  annotations:
    cert-manager.io/cluster-issuer: {{ .Values.clusterIssuer }}
spec:
  tls:
    - secretName: teri-coaching-tls
      hosts:
        - {{ .Values.host }}
        {{- range .Values.extraHosts }}
        - {{ . }}
        {{- end }}
  rules:
    - host: {{ .Values.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teri-coaching
                port:
                  number: 80
    {{- range .Values.extraHosts }}
    - host: {{ . }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: teri-coaching
                port:
                  number: 80
    {{- end }}
